// Code generated by hertz generator.

package hello

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			hlog.CtxInfof(ctx, "[Root中间件] method=%s path=%s", c.Request.Header.Method(), c.Request.URI().Path())
			c.Next(ctx)
		},
	}
}

func _hellomethodMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			hlog.CtxInfof(ctx, "[Hello中间件] method=%s path=%s", c.Request.Header.Method(), c.Request.URI().Path())
			c.Next(ctx)
		},
	}
}

func _newmethodMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			hlog.CtxInfof(ctx, "[New中间件] method=%s path=%s", c.Request.Header.Method(), c.Request.URI().Path())
			c.Next(ctx)
		},
	}
}

func _othermethodMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			hlog.CtxInfof(ctx, "[Other中间件] method=%s path=%s", c.Request.Header.Method(), c.Request.URI().Path())
			c.Next(ctx)
		},
	}
}
