// Code generated by hertz generator.

package hello

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// 模拟请求结构
type MockReq struct {
	Name string `json:"name"`
}

// 模拟响应结构
type MockResp struct {
	Message string `json:"message"`
	Code    int    `json:"code"`
}

// NewMethod .
// @router /new [GET]
func NewMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req MockReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := &MockResp{
		Message: "Hello " + req.Name,
		Code:    200,
	}

	c.JSON(consts.StatusOK, resp)
}
