package router

import (
	"PrimeGo/biz/handler"
	hello "PrimeGo/biz/router/hello"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	hello.Register(r)

}

// customizeRegister registers customize routers.
func RootRegister(r *server.Hertz) {
	// your code ...
	root := r.Group("/")
	root.GET("/", handler.Ping)
}

// register registers all routers.
func Register(r *server.Hertz) {
	RootRegister(r)
	GeneratedRegister(r)
}
